name: Deploy DevOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout código
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t devops-cicd .

    - name: Deploy container
      run: |
        docker stop devops-cicd || true
        docker rm devops-cicd || true
        docker run -d -p 80:80 --name devops-cicd devops-cicd
